function umgSlide(h,f){if(h.substring(0,1)!="#")h="#"+h;h+=" ";this.source=h;this.dest=f;var d=this;this.umg_instancename="slide";this.umg_slideTimeout=5;this.umg_slideTimePassed=0;this.umg_index=-1;this.umg_naviInited=false;this.umg_xofysplitter=" / ";this.umg_mouseoverbehavior="";this.umg_loopplay=true;jQuery(h).css("display","none");this.umg_freetextslide=false;this.umg_images=jQuery(h+" .image");this.umg_titles=jQuery(h+" .title");this.umg_descriptions=jQuery(h+" .description");this.umg_links=
jQuery(h+" .link");this.umg_tags=jQuery(h+" .tags");this.umg_authors=jQuery(h+" .author");this.umg_takendates=jQuery(h+" .takendate");this.umg_umgids=jQuery(h+" .umgid");this.umg_container=jQuery("#umg_container"+f);this.umg_largelist=jQuery("#umg_largelist"+f);this.umg_large=jQuery("#umg_large"+f);this.umg_caption=jQuery("#umg_caption"+f);this.umg_captiontext=jQuery("#umg_captiontext"+f);this.umg_more=jQuery("#umg_more"+f);this.umg_buttons=jQuery("#umg_buttons"+f);this.umg_prev=jQuery("#umg_prev"+
f);this.umg_next=jQuery("#umg_next"+f);this.umg_play=jQuery("#umg_play"+f);this.umg_navi=jQuery("#umg_navi"+f);this.umg_countdown=jQuery("#umg_countdown"+f);this.umg_loading=jQuery("#umg_loading"+f);this.umg_thumbs=jQuery("#umg_thumbs"+f);this.umg_thumbslist=jQuery("#umg_thumbslist"+f);this.umg_xofy=jQuery("#umg_xofy"+f);this.umg_container.css("display","block");this.umg_prev.length>0&&this.umg_prev.click(function(){d.navigateTo(d.umg_index-1)});this.umg_next.length>0&&this.umg_next.click(function(){d.navigateTo(d.umg_index+
1)});this.umg_play.length>0&&this.umg_play.click(function(){d.umg_slideTimePassed=d.umg_slideTimeout;d.umg_playing?d.stopAutoPlay():d.autoPlay()});this.umg_countdown.length>0&&this.umg_countdown.click(function(){d.stopAutoPlay()});this.play=function(a){var b=true;if(a){if(a.autoPlay)b=a.autoPlay.toLowerCase()=="true";if(a.slideTimeout)this.umg_slideTimeout=a.slideTimeout;if(a.mouseOver)this.umg_mouseoverbehavior=a.mouseOver.toLowerCase();if(a.loopPlay)this.umg_loopplay=a.loopPlay.toLowerCase()=="loop";
if(a.keyboardControl!="DonotUse"){jQuery(document).keydown(function(e){e.keyCode==37&&d.navigateTo(d.umg_index-1);e.keyCode==39&&d.navigateTo(d.umg_index+1)});jQuery(this.umg_container).mousewheel(function(e,k){if(k>0)d.navigateTo(d.umg_index-1);else k<0&&d.navigateTo(d.umg_index+1);return false})}if(a.disabledControls)for(var c=a.disabledControls.split(","),i=0;i<c.length;i++){var g=jQuery("#umg_"+c[i].toLowerCase()+f);if(g.length>0){g.css("display","none");g.css("visibility","hidden")}}if(a.easing!=
""&&a.easing!="swing")jQuery.easing.def=a.easing;if(a.mode=="Freetext")this.umg_freetextslide=true}this.umg_thumbs.css("display")!="none"&&this.buildThumbList&&this.buildThumbList();this.moveTo(0);if(b>0){if(this.umg_countdown.css("display")!="none"){this.umg_countdown.attr("visiblebefore","true");this.umg_countdown.hide()}this.autoPlay()}else this.stopAutoPlay()};this.autoPlay=function(){var a;a=this.umg_freetextslide?this.umg_titles:this.umg_images;if(!(a.length<=1)){this.umg_playing=true;this.umg_index==
a.length-1&&this.moveTo(0);this.umg_interval=window.setInterval(this.umg_instancename+f+".onInterval()",1E3);this.umg_play&&this.umg_play.addClass("active")}};this.stopAutoPlay=function(){this.umg_playing=false;window.clearInterval(this.umg_interval);this.umg_play&&this.umg_play.removeClass("active");if(this.umg_countdown.css("display")!="none"){this.umg_countdown.hide();this.umg_countdown.attr("visiblebefore","true")}};this.onInterval=function(){if(!this.umg_isloading){this.umg_slideTimePassed+=
1;if(this.umg_slideTimePassed>=this.umg_slideTimeout){this.umg_slideTimePassed=0;this.umg_index+1>=(this.umg_freetextslide?this.umg_titles:this.umg_images).length&&!this.umg_loopplay?this.stopAutoPlay():this.moveTo(this.umg_index+1)}if(this.umg_countdown.css("display")!="none"||this.umg_countdown.attr("visiblebefore")=="true")if(this.umg_slideTimePassed==0){this.umg_countdown.hide();this.umg_countdown.attr("visiblebefore","true")}else{this.umg_countdown.show();this.umg_countdown.html(
this.umg_slideTimeout-this.umg_slideTimePassed)}}};this.getResizedResolution=function(a){var b=Math.max(a.width/a.maxWidth,a.height/a.maxHeight),c=Math.round(a.height/b);a.newWidth=Math.round(a.width/b);a.newHeight=c};this.getPrioritySize=function(a){var b={};b.width=a.width();b.height=a.height();b.priorityhdir=a.css("priority-hdir");b.priorityvdir=a.css("priority-vdir");var c=a.css("priority-width");a=a.css("priority-height");if(c){if(c.indexOf("px")>0)c=c.substring(0,c.indexOf("px"));b.prioritywidth=
c*1}else b.prioritywidth=b.width;if(a){if(a.indexOf("px")>0)a=a.substring(0,a.indexOf("px"));b.priorityheight=a*1}else b.priorityheight=b.height;return b};this.getSuggestedPosition=function(a){var b={};b.suggestedX=0;b.suggestedY=0;var c=this.getPrioritySize(this.umg_large);if(a.width()<=c.width)if(c.priorityhdir=="right")b.suggestedX=a.width()<=c.prioritywidth?(c.prioritywidth-a.width())/2+c.width-c.prioritywidth:c.width-a.width();else if(a.width()<=c.prioritywidth)b.suggestedX=(c.prioritywidth-
a.width())/2;if(a.height()<=c.height)if(c.priorityvdir=="bottom")b.suggestedY=a.height()<=c.priorityheight?(c.priorityheight-a.height())/2+c.height-c.priorityheight:c.height-a.height();else if(a.height()<=c.priorityheight)b.suggestedY=(c.priorityheight-a.height())/2;return b};this.navigateTo=function(a){this.umg_playing&&this.stopAutoPlay();a!=this.umg_index&&this.moveTo(a)};this.moveTo=function(a){var b;b=this.umg_freetextslide?this.umg_titles:this.umg_images;if(a>=b.length)a=0;else if(a<0)a=b.length-
1;this.umg_slideTimePassed=0;var c=jQuery(b[a]);if(c.length<1){alert("No slides in gallery "+this.dest);this.stopAutoPlay()}else{var i=this.umg_large.find("#img"+this.umg_index),g=this.umg_large.find("#img"+a);if(this.umg_freetextslide){if(g.length==0){this.umg_large.append("<div class='freetext' id='img"+a+"' style='display:none' index='"+a+"' />");g=this.umg_large.find("#img"+a);g.html(jQuery(this.umg_descriptions[a]).html());d.umg_transition_freetext_align(g)}d.umg_transition_freetext_activate(g,
i)}else{var e=c.attr("largeurl");e||(e=c.attr("src"));if(g.length==0){this.umg_large.append("<img class='image' id='img"+a+"' style='display:none' index='"+a+"' />");g=this.umg_large.find("#img"+a);c=new Image;c.onload=function(){var j=d.umg_large.width(),l=d.umg_large.height();if(this.width>j||this.height>l){j={width:this.width,maxWidth:j,height:this.height,maxHeight:l};d.getResizedResolution(j);g.attr("width",j.newWidth);g.attr("height",j.newHeight)}else{g.attr("width",this.width);g.attr("height",
this.height)}d.umg_loading&&d.umg_loading.removeClass("active");d.umg_isloading=false;d.umg_transition_image_align(this,g);d.umg_transition_image_activate(g,i)};this.umg_loading&&this.umg_loading.addClass("active");this.umg_isloading=true;c.src=e}else this.umg_transition_image_activate(g,i);this.umg_captiontext&&this.umg_transition_caption_do(a);e=jQuery(this.umg_links[a]).attr("href");if(this.umg_more&&e){this.umg_more.attr("href",e);this.umg_more.show()}else this.umg_more.hide()}if(typeof UPG_onPhotoLoad!=
"undefined"){e=jQuery(this.umg_umgids[a]).html();UPG_onPhotoLoad(e)}typeof this.onMoveTo!="undefined"&&this.onMoveTo(a);this.umg_index=a;if(this.umg_navi){e="";for(c=0;c<b.length;c++){var k="";k=c==a?"<a href='javascript:void(0);' class='active'></a>":"<a href='javascript:void(0);' onclick='slide"+f+".navigateTo("+c+")'></a>";e+=k}this.umg_navi.html(e);if(!this.umg_naviInited){this.umg_naviInited=true;e=this.umg_navi.find("a");e=jQuery(e[e.length-1]);this.umg_navi.css("width",
e.position().left+e.width()+6)}}this.umg_xofy.length>0&&this.umg_xofy.html(a+1+this.umg_xofysplitter+b.length)}};this.updateCaption=function(a){if(this.umg_captiontext.originalWidth){this.umg_captiontext.css("width",this.umg_captiontext.originalWidth);this.umg_captiontext.css("height",this.umg_captiontext.originalHeight)}else{this.umg_captiontext.originalWidth=this.umg_captiontext.width();var b=this.umg_captiontext.height();if(b<=0)b=this.umg_caption.height();this.umg_captiontext.originalHeight=
b}this.umg_captiontext.find("#umg_captiontitle"+this.dest).html(jQuery(this.umg_titles[a]).html());this.umg_captiontext.find("#umg_captiondescription"+this.dest).html(jQuery(this.umg_descriptions[a]).html());b=this.umg_captiontext.find("#umg_captionauthor"+this.dest);b.length>0&&b.html(jQuery(this.umg_authors[a]).html());b=this.umg_captiontext.find("#umg_captiontakendate"+this.dest);b.length>0&&b.html(jQuery(this.umg_takendates[a]).html());
b=this.umg_captiontext.find("#umg_captiontags"+this.dest);b.length>0&&b.html(jQuery(this.umg_tags[a]).html())};typeof this.umg_init!="undefined"&&this.umg_init(sender)};
