<div>  
  <div class="row"><div class="medium-12 columns"><div id="FooterTopPane" runat="server"></div></div></div>

  <div class="row">
    <div class="medium-3 columns"><div id="Footer1Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer2Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer3Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer4Pane" runat="server"></div></div>
  </div>

  <div class="row"><div class="medium-12 columns"><div id="FooterBottomPane" runat="server"></div></div></div>

  <div class="row">
    <div class="medium-12 columns">
      <hr />
    </div>
  </div>
</div>