<div>  
  <div class="row"><div class="medium-12 columns"><div id="FooterTopPane" runat="server"></div></div></div>

  <div class="row">
    <div class="medium-3 columns"><div id="Footer1Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer2Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer3Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer4Pane" runat="server"></div></div>
  </div>

  <div class="row"><div class="medium-12 columns"><div id="FooterBottomPane" runat="server"></div></div></div>

  <div class="row">
    <div class="medium-4 columns small-text-center medium-text-left">
      <ul class="footerList">
        <li class="footerTitle">About Us</li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Who-are-we.aspx">Who Are We</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Jobs-at-Summer-Festival-Guide.aspx">Jobs at Summer Festival Guide</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Contact-Us.aspx">Contact Us</a>
        </li>
      </ul>
    </div>
    <div class="medium-4 columns small-text-center medium-text-center">
      <ul class="footerList">
        <li class="footerTitle">Good Stuff</li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Festival-News.aspx">Festival News</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Event-Calendar.aspx">Event Calendar</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Reviews.aspx">Reviews</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Interviews.aspx">Interviews</a>
        </li>
      </ul>
    </div>
    <div class="medium-4 columns small-text-center medium-text-right">
      <ul class="footerList">
        <li class="footerTitle">Essentials</li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Tickets.aspx">Festival Tickets</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Competitions.aspx">Competitions</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="http://www.summerfestivalguide.co.uk/Survival-Guide.aspx">Survival Guide</a>
        </li>
      </ul>
    </div>
  </div>
  
  <div class="row">
    <div class="medium-12 columns">
      <hr />
    </div>
  </div>
</div>