<div>

  <div class="row">
    <div class="small-text-center medium-6 columns medium-text-left">
      <dnn:PRIVACY ID="dnnPrivacy" runat="server" CssClass="footerLink" />
      <asp:Label ID="Label1" runat="server" Text="&nbsp;|&nbsp;" CssClass="footerLink"></asp:Label>
      <dnn:TERMS ID="dnnTerms" runat="server"  CssClass="footerLink" />
    </div>
    <div class="small-text-center medium-6 columns medium-text-right">
      <dnn:COPYRIGHT ID="dnnCopyright" runat="server" CssClass="footerLink" /><br />
      <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="http://www.dnnconsulting.nl" Target="_blank" CssClass="footerLink">Skin by DnnConsulting.nl</asp:HyperLink>
    </div>
  </div>
  
</div>
